export default {
  AUTH: {
    LOGIN: 'LOGIN_AUTH',
    LOGOUT: 'LOGOUT_AUTH',
  },
  CLEAR: {
    OS: 'CLEAR_OS',
    PROVIDER: 'CLEAR_PROVIDER',
    TECNICO: 'CLEAR_TECNICO',
  },
  EDITAR: {
    PROVIDER: 'EDITAR_PROVIDER',
  },
  REDIRECT: {
    ENTRADA: 'INICIAL_STATE_REDIRECT_ENTRADA',
    FORNECEDOR: 'INICIAL_STATE_REDIRECT_FORNECEDOR',
    OS: 'SET_VALUE_OS_UPDATE',
    PRODUTO: 'INICIAL_STATE_REDIRECT_PRODUTO',
    TECNICO: 'INICIAL_STATE_REDIRECT_TECNICO',
  },
}
