export default {
  CLEAR: {
    OS: 'CLEAR_OS',
    PROVIDER: 'CLEAR_PROVIDER',
    TECNICO: 'CLEAR_TECNICO',
  },
  EDITAR: {
    PROVIDER: 'EDITAR_PROVIDER',
  },
  LOGIN: {
    AUTH: 'LOGIN_AUTH',
    CHANGE_VALUE: 'LOGIN_CHANGE_VALUE',
    LOGOUT: 'LOGOUT_AUTH',
  },

  REDIRECT: {
    ENTRADA: 'INICIAL_STATE_REDIRECT_ENTRADA',
    FORNECEDOR: 'INICIAL_STATE_REDIRECT_FORNECEDOR',
    OS: 'SET_VALUE_OS_UPDATE',
    PRODUTO: 'INICIAL_STATE_REDIRECT_PRODUTO',
    TECNICO: 'INICIAL_STATE_REDIRECT_TECNICO',
    USUARIO: 'INICIAL_STATE_REDIRECT_USUARIO',
  },
}
